apiVersion: v1
kind: Namespace
metadata:
  name: demo2
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  namespace: demo2
  name: podinfo
spec:
  chart:
    repository: https://stefanprodan.github.io/podinfo
    name: podinfo
    version: 3.2.0
  values:
    image:
      repository: stefanprodan/podinfo
      tag: 3.2.1
