apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow-controller-leader-election
rules:
- apiGroups:
  - coordination.k8s.io/v1
  resources:
  - leases
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io/v1
  resources:
  - leases
  resourceNames:
  - workflow-controller
  verbs:
  - get
  - update
  - delete
