apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ambassador
spec:
  releaseName: ambassador
  interval: 1m
  install:
    skipCRDs: true
  chart:
    spec:
      chart: ambassador
      version: 6.6.2
      sourceRef:
        kind: HelmRepository
        name: ambassador
  values:
    image:
      repository: quay.io/datawire/ambassador
      tag: 1.12.2
    crds:
      create: true
      enabled: true
      keep: false
    scope:
      singleNamespace: true
    enableAES: false
    authService:
      create: false
    service:
      type: NodePort
      ports:
      - name: http
        port: 80
        hostPort: 80
        targetPort: 8080
      - name: https
        port: 443
        hostPort: 443
        targetPort: 8443
    deploymentStrategy:
      type: Recreate
    autoscaling:
      enabled: false
    replicaCount: 1
    resources:
      requests:
        cpu: 25m
        memory: 150Mi
      limits:
        # CPU limit is left unset until we need it (e.g., we experience
        # issues with runaway CPU consumption).
        memory: 250Mi
