apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
spec:
  releaseName: podinfo
  interval: 1m
  chart:
    spec:
      chart: poodinfo
      version: 3.2.0
      sourceRef:
        kind: HelmRepository
        name: podinfo
