apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
spec:
  interval: 1m0s
  path: live/podinfo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-demo
  validation: client
