apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-demo
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux-system # The secret has to be created externally
  url: https://github.com/vladlosev/flux-demo
